apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  type: LoadBalancer
  selector:
    app: proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: mongo-express
      protocol: TCP
      port: 81
      targetPort: 81
